/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import cinema.*;
import javax.swing.ImageIcon;

/**
 *
 * @author esmil
 */
public class MoviePage extends javax.swing.JFrame {

    /**
     * Creates new form MoviePage
     */
    public MoviePage() {
        initComponents();//on charge les composants du front
       
         MyProfilebtn.setVisible(false);//de base on afficher des deux boutons
           connexion.setVisible(false);
           System.out.println(""+Projet.connectid);
        if(Projet.connectid>0) // si client connecté
        {
        MyProfilebtn.setVisible(true);//on affiche que le bouton my profile
      connexion.setVisible(false);// on garde non affiché le bouton connexion
        }
        else
        {
       MyProfilebtn.setVisible(false);// on garde non affiché le bouton connexion
       connexion.setVisible(true);//on affiche que le bouton connexion
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FilmDAO movie = new FilmDAOImp();

        Films Movie1 = new Films();
        Films Movie2 = new Films();
        Films Movie3 = new Films();
        Films Movie4 = new Films();
        Films Movie5 = new Films();
        Films Movie6 = new Films();

        Movie1 = movie.getFilmsID(Projet.FilmID1);
        Movie2 = movie.getFilmsID(Projet.FilmID2);
        Movie3 = movie.getFilmsID(Projet.FilmID3);
        Movie4 = movie.getFilmsID(Projet.FilmID4);
        Movie5 = movie.getFilmsID(Projet.FilmID5);
        Movie6 = movie.getFilmsID(Projet.FilmID6);

        ImageIcon Format1 =null;
        ImageIcon Format2 =null;
        ImageIcon Format3 =null;
        ImageIcon Format4 =null;
        ImageIcon Format5 =null;
        ImageIcon Format6 =null;
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Affiche1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        byte[] imagedata =Movie1.getphoto();
        Format1 = new ImageIcon(imagedata);
        jLabel3 = new javax.swing.JLabel();
        Affiche2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        byte[] imagedata2 =Movie2.getphoto();
        Format2 = new ImageIcon(imagedata2);
        jLabel2 = new javax.swing.JLabel();
        Affiche3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        byte[] imagedata3 =Movie3.getphoto();
        Format3 = new ImageIcon(imagedata3);
        jLabel4 = new javax.swing.JLabel();
        Affiche4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        byte[] imagedata4 =Movie4.getphoto();
        Format4 = new ImageIcon(imagedata4);
        jLabel5 = new javax.swing.JLabel();
        MovieName1 = new javax.swing.JLabel();
        MovieYear1 = new javax.swing.JLabel();
        MovieName2 = new javax.swing.JLabel();
        MovieYear2 = new javax.swing.JLabel();
        MovieName3 = new javax.swing.JLabel();
        MovieYear3 = new javax.swing.JLabel();
        MovieYear4 = new javax.swing.JLabel();
        MovieName4 = new javax.swing.JLabel();
        Runtime1 = new javax.swing.JLabel();
        Runtime2 = new javax.swing.JLabel();
        Runtime3 = new javax.swing.JLabel();
        Runtime4 = new javax.swing.JLabel();
        MovieName5 = new javax.swing.JLabel();
        MovieYear5 = new javax.swing.JLabel();
        Affiche5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        byte[] imagedata5 =Movie5.getphoto();
        Format5 = new ImageIcon(imagedata5);
        jLabel6 = new javax.swing.JLabel();
        Runtime5 = new javax.swing.JLabel();
        MovieYear6 = new javax.swing.JLabel();
        MovieName6 = new javax.swing.JLabel();
        Affiche6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        byte[] imagedata6 =Movie6.getphoto();
        Format6 = new ImageIcon(imagedata6);
        jLabel7 = new javax.swing.JLabel();
        Runtime6 = new javax.swing.JLabel();
        BoutonMovie1 = new javax.swing.JButton();
        BoutonMovie3 = new javax.swing.JButton();
        BoutonMovie2 = new javax.swing.JButton();
        BoutonMovie4 = new javax.swing.JButton();
        BoutonMovie5 = new javax.swing.JButton();
        BoutonMovie6 = new javax.swing.JButton();
        connexion = new javax.swing.JButton();
        MyProfilebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 240, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BackButton.setBackground(new java.awt.Color(0, 0, 0));
        BackButton.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 0));
        jLabel1.setText("MOVIES");

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setIcon(Format1);
        jLabel3.setText(null);
        jScrollPane1.setViewportView(jLabel3);

        javax.swing.GroupLayout Affiche1Layout = new javax.swing.GroupLayout(Affiche1);
        Affiche1.setLayout(Affiche1Layout);
        Affiche1Layout.setHorizontalGroup(
            Affiche1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Affiche1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        Affiche1Layout.setVerticalGroup(
            Affiche1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Affiche1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setIcon(Format2);
        jLabel2.setText(null);
        jScrollPane2.setViewportView(jLabel2);

        javax.swing.GroupLayout Affiche2Layout = new javax.swing.GroupLayout(Affiche2);
        Affiche2.setLayout(Affiche2Layout);
        Affiche2Layout.setHorizontalGroup(
            Affiche2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Affiche2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Affiche2Layout.setVerticalGroup(
            Affiche2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Affiche2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setIcon(Format3);
        jLabel4.setText(null);
        jScrollPane3.setViewportView(jLabel4);

        javax.swing.GroupLayout Affiche3Layout = new javax.swing.GroupLayout(Affiche3);
        Affiche3.setLayout(Affiche3Layout);
        Affiche3Layout.setHorizontalGroup(
            Affiche3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Affiche3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        Affiche3Layout.setVerticalGroup(
            Affiche3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Affiche3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setIcon(Format4);
        jLabel5.setText(null);
        jScrollPane4.setViewportView(jLabel5);

        javax.swing.GroupLayout Affiche4Layout = new javax.swing.GroupLayout(Affiche4);
        Affiche4.setLayout(Affiche4Layout);
        Affiche4Layout.setHorizontalGroup(
            Affiche4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Affiche4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        Affiche4Layout.setVerticalGroup(
            Affiche4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Affiche4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        MovieName1.setFont(new java.awt.Font("Showcard Gothic", 0, 16)); // NOI18N
        MovieName1.setForeground(new java.awt.Color(240, 240, 0));
        MovieName1.setText(Movie1.getTitle());

        MovieYear1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MovieYear1.setForeground(new java.awt.Color(240, 240, 0));
        MovieYear1.setText(String.valueOf(Projet.FilmID1));

        MovieName2.setFont(new java.awt.Font("Showcard Gothic", 0, 16));
        MovieName2.setForeground(new java.awt.Color(240, 240, 0));
        MovieName2.setText(Movie2.getTitle());

        MovieYear2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MovieYear2.setForeground(new java.awt.Color(240, 240, 0));
        MovieYear2.setText(String.valueOf(Projet.FilmID2));

        MovieName3.setFont(new java.awt.Font("Showcard Gothic", 0, 16
        ));
        MovieName3.setForeground(new java.awt.Color(240, 240, 0));
        MovieName3.setText(Movie3.getTitle());

        MovieYear3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MovieYear3.setForeground(new java.awt.Color(240, 240, 0));
        MovieYear3.setText(String.valueOf(Projet.FilmID3));

        MovieYear4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MovieYear4.setForeground(new java.awt.Color(240, 240, 0));
        MovieYear4.setText(String.valueOf(Projet.FilmID4));

        MovieName4.setFont(new java.awt.Font("Showcard Gothic", 0, 16));
        MovieName4.setForeground(new java.awt.Color(240, 240, 0));
        MovieName4.setText(Movie4.getTitle());

        Runtime1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Runtime1.setForeground(new java.awt.Color(240, 240, 0));
        Runtime1.setText(Movie1.getTime());

        Runtime2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Runtime2.setForeground(new java.awt.Color(240, 240, 0));
        Runtime2.setText(Movie2.getTime());

        Runtime3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Runtime3.setForeground(new java.awt.Color(240, 240, 0));
        Runtime3.setText(Movie3.getTime());

        Runtime4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Runtime4.setForeground(new java.awt.Color(240, 240, 0));
        Runtime4.setText(Movie4.getTime());

        MovieName5.setFont(new java.awt.Font("Showcard Gothic", 0, 16));
        MovieName5.setForeground(new java.awt.Color(240, 240, 0));
        MovieName5.setText(Movie5.getTitle());

        MovieYear5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MovieYear5.setForeground(new java.awt.Color(240, 240, 0));
        MovieYear5.setText(String.valueOf(Projet.FilmID5));

        jLabel6.setIcon(Format5);
        jScrollPane5.setViewportView(jLabel6);

        javax.swing.GroupLayout Affiche5Layout = new javax.swing.GroupLayout(Affiche5);
        Affiche5.setLayout(Affiche5Layout);
        Affiche5Layout.setHorizontalGroup(
            Affiche5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Affiche5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );
        Affiche5Layout.setVerticalGroup(
            Affiche5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Affiche5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        Runtime5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Runtime5.setForeground(new java.awt.Color(240, 240, 0));
        Runtime5.setText(Movie5.getTime());

        MovieYear6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MovieYear6.setForeground(new java.awt.Color(240, 240, 0));
        MovieYear6.setText(String.valueOf(Projet.FilmID6));

        MovieName6.setFont(new java.awt.Font("Showcard Gothic", 0, 16));
        MovieName6.setForeground(new java.awt.Color(240, 240, 0));
        MovieName6.setText(Movie6.getTitle());

        jLabel7.setIcon(Format6);
        jScrollPane6.setViewportView(jLabel7);

        javax.swing.GroupLayout Affiche6Layout = new javax.swing.GroupLayout(Affiche6);
        Affiche6.setLayout(Affiche6Layout);
        Affiche6Layout.setHorizontalGroup(
            Affiche6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Affiche6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );
        Affiche6Layout.setVerticalGroup(
            Affiche6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Affiche6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        Runtime6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Runtime6.setForeground(new java.awt.Color(240, 240, 0));
        Runtime6.setText(Movie6.getTime());

        BoutonMovie1.setBackground(new java.awt.Color(0, 0, 0));
        BoutonMovie1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        BoutonMovie1.setText("J'y vais");
        BoutonMovie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonMovie1ActionPerformed(evt);
            }
        });

        BoutonMovie3.setBackground(new java.awt.Color(0, 0, 0));
        BoutonMovie3.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        BoutonMovie3.setText("J'y vais");
        BoutonMovie3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonMovie3ActionPerformed(evt);
            }
        });

        BoutonMovie2.setBackground(new java.awt.Color(0, 0, 0));
        BoutonMovie2.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        BoutonMovie2.setText("J'y vais");
        BoutonMovie2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonMovie2ActionPerformed(evt);
            }
        });

        BoutonMovie4.setBackground(new java.awt.Color(0, 0, 0));
        BoutonMovie4.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        BoutonMovie4.setText("J'y vais");
        BoutonMovie4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonMovie4ActionPerformed(evt);
            }
        });

        BoutonMovie5.setBackground(new java.awt.Color(0, 0, 0));
        BoutonMovie5.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        BoutonMovie5.setText("J'y vais");
        BoutonMovie5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonMovie5ActionPerformed(evt);
            }
        });

        BoutonMovie6.setBackground(new java.awt.Color(0, 0, 0));
        BoutonMovie6.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        BoutonMovie6.setText("J'y vais");
        BoutonMovie6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonMovie6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MovieName1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(Affiche1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(Runtime1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(BoutonMovie1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(89, 89, 89)
                                                .addComponent(MovieYear2))
                                            .addComponent(MovieName2, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                            .addComponent(Affiche2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(BoutonMovie2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Runtime2)
                                .addGap(62, 62, 62)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Affiche3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MovieName3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addComponent(Runtime3)))
                                        .addGap(0, 15, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(BoutonMovie3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(MovieYear1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MovieYear3)
                        .addGap(97, 97, 97)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(BoutonMovie4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(Runtime4))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(MovieName4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                        .addComponent(Affiche4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(Affiche5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(MovieName5, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Affiche6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MovieName6, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 41, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(BoutonMovie5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156)
                                .addComponent(BoutonMovie6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(Runtime5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Runtime6)
                                .addGap(102, 102, 102))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(MovieYear4)
                        .addGap(219, 219, 219)
                        .addComponent(MovieYear5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MovieYear6)
                        .addGap(118, 118, 118))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(180, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MovieYear4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MovieYear5)
                            .addComponent(MovieYear6))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Affiche5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Affiche4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Runtime4)
                                    .addComponent(Runtime3)
                                    .addComponent(Runtime2)
                                    .addComponent(Runtime1)
                                    .addComponent(Runtime5)
                                    .addComponent(Runtime6)))
                            .addComponent(Affiche6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BoutonMovie6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BoutonMovie3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BoutonMovie4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BoutonMovie5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MovieYear1)
                                    .addComponent(MovieYear3))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Affiche1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Affiche3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MovieName2)
                                    .addComponent(MovieName1)
                                    .addComponent(MovieName3)
                                    .addComponent(MovieName4)
                                    .addComponent(MovieName5)
                                    .addComponent(MovieName6))
                                .addGap(32, 32, 32)
                                .addComponent(MovieYear2)
                                .addGap(21, 21, 21)
                                .addComponent(Affiche2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BoutonMovie1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoutonMovie2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(69, 69, 69))
        );

        connexion.setBackground(new java.awt.Color(0, 0, 0));
        connexion.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        connexion.setForeground(new java.awt.Color(240, 240, 0));
        connexion.setText("Connexion");
        connexion.setToolTipText("");
        connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connexionActionPerformed(evt);
            }
        });

        MyProfilebtn.setBackground(new java.awt.Color(0, 0, 0));
        MyProfilebtn.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        MyProfilebtn.setForeground(new java.awt.Color(240, 240, 0));
        MyProfilebtn.setText("My Profile");
        MyProfilebtn.setToolTipText("");
        MyProfilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyProfilebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(655, 655, 655)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(connexion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MyProfilebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(connexion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MyProfilebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)))
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 106, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        WelcomePage a = new WelcomePage();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void BoutonMovie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonMovie1ActionPerformed
        // TODO add your handling code here:
        MovieDetails a = new MovieDetails(Projet.FilmID1);
        a.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BoutonMovie1ActionPerformed

    private void connexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connexionActionPerformed
        // TODO add your handling code here:
        SignInPage a = new SignInPage();
        a.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_connexionActionPerformed

    private void BoutonMovie3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonMovie3ActionPerformed
        // TODO add your handling code here:

        MovieDetails a = new MovieDetails(Projet.FilmID3);
        a.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BoutonMovie3ActionPerformed

    private void BoutonMovie2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonMovie2ActionPerformed
        // TODO add your handling code here:
        MovieDetails a = new MovieDetails(Projet.FilmID2);
        a.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BoutonMovie2ActionPerformed

    private void BoutonMovie4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonMovie4ActionPerformed
        // TODO add your handling code here:
        MovieDetails a = new MovieDetails(Projet.FilmID4);
        a.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BoutonMovie4ActionPerformed

    private void BoutonMovie5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonMovie5ActionPerformed
        // TODO add your handling code here:
        MovieDetails a = new MovieDetails(Projet.FilmID5);
        a.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BoutonMovie5ActionPerformed

    private void BoutonMovie6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonMovie6ActionPerformed
        // TODO add your handling code here:
        MovieDetails a = new MovieDetails(Projet.FilmID6);
        a.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BoutonMovie6ActionPerformed

    private void MyProfilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyProfilebtnActionPerformed
        // TODO add your handling code here:
         ClientAccountPage a= new ClientAccountPage();
         a.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_MyProfilebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoviePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoviePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoviePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoviePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoviePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Affiche1;
    private javax.swing.JPanel Affiche2;
    private javax.swing.JPanel Affiche3;
    private javax.swing.JPanel Affiche4;
    private javax.swing.JPanel Affiche5;
    private javax.swing.JPanel Affiche6;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BoutonMovie1;
    private javax.swing.JButton BoutonMovie2;
    private javax.swing.JButton BoutonMovie3;
    private javax.swing.JButton BoutonMovie4;
    private javax.swing.JButton BoutonMovie5;
    private javax.swing.JButton BoutonMovie6;
    private javax.swing.JLabel MovieName1;
    private javax.swing.JLabel MovieName2;
    private javax.swing.JLabel MovieName3;
    private javax.swing.JLabel MovieName4;
    private javax.swing.JLabel MovieName5;
    private javax.swing.JLabel MovieName6;
    private javax.swing.JLabel MovieYear1;
    private javax.swing.JLabel MovieYear2;
    private javax.swing.JLabel MovieYear3;
    private javax.swing.JLabel MovieYear4;
    private javax.swing.JLabel MovieYear5;
    private javax.swing.JLabel MovieYear6;
    private javax.swing.JButton MyProfilebtn;
    private javax.swing.JLabel Runtime1;
    private javax.swing.JLabel Runtime2;
    private javax.swing.JLabel Runtime3;
    private javax.swing.JLabel Runtime4;
    private javax.swing.JLabel Runtime5;
    private javax.swing.JLabel Runtime6;
    private javax.swing.JButton connexion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
